### ISSUE TITLE
BWP Sitemaps Not Clearing Cache on New Posts/Updates

### ISSUE THREAD

**Issue by casbboy** [szepeviktor/fix-w3tc#187]
Weird issue. Just noticed that our BWP Sitemaps are not getting cleared from cache when we add a new article. Not sure why fix-w3tc is not clearing the cache on BWP with new updates. I've been having to manually clear disk cache for every new post.

Any ideas?

Cheers
Ryan

**Comment by nigrosimone** [comment]
Please post here your w3tc-config (uses the export setting feature in the admin dashboard).

**Comment by nigrosimone** [comment]
And.. some info:
1) wordpress version (4.6? ) ? 
2) web service tecnology (apache... ) ? 
3) fix-w3tc version (latest? ) ?

**Comment by amiga-500** [comment]
Hi Ryan ( @casbboy )...Just installed BWP (Better WordPress Google XML) Sitemaps plugin and played around.  Question:

- When you say you have to _"manually clear disk cache for every new post"_  i assume you mean you are having to click the BWP <kbd>Flush Cache</kbd> button so that the sitemap is regenerated.  Correct?

In my tests i too noticed the sitemap cache (handled by BWP's _Sitemap Cache_ feature) is never regenerated.

Interestingly, when i disable fix-w3tc BWP Sitemaps still _**does not**_ clear the cache on new article posts.

If that is the case it appears it may be a bug in BMP -- maybe it stopped working because Wordpress updated to 4.7 yesterday?

**Comment by casbboy** [comment]
Hello!

Let me get you that info. I had the issue with 4.6, and discovered with that version. I updated to 4.7 today. I would go to the Dashboard and manually click Flush Disk Cache.

1. wordpress version( 4.6, now 4.7)
2. Web service (nginx, disk cache)
3. fix-w3tc (.9.4.5)

I'm not sure how to export the settings. "Performance >> ?"

Cheers!
Ryan

**Comment by amiga-500** [comment]
Export is located under fix-w3tc's _Performance > General Settings > Import/Export Settings_ (located at the very bottom of the page). Just click the _Download_ button

**Comment by casbboy** [comment]
Here you go :)
[export-w3.txt](https://github.com/szepeviktor/fix-w3tc/files/638149/export-w3.txt)

**Comment by amiga-500** [comment]
Located under: _Performance > Page Cache > Purge Policy:Page Cache_ there is a field labelled: **Purge Sitemaps**

In that field replace its present content with this: 
```php
[a-z0-9_\-]*sitemap[a-z0-9_\-]*\.(xml|xsl|html?)(\.gz)?|post\.xml|site\.xml|page\.xml|taxonomy_category\.xml
```
Let me know if that solves your problem.

**Comment by casbboy** [comment]
Thanks! I'm testing right now....

**Comment by casbboy** [comment]
Worked on post.xml sitemap! But it didn't on this: sitemapindex.xml

**Comment by amiga-500** [comment]
Hi @casbboy thats strange about _sitemapindex.xml_ since the line above would have included that (even in my test it covered it).  But nonetheless, lets make it very specific then.  So replace the line with: 

```php
(sitemapindex|site|page|taxonomy_category)\.xml
```

**Comment by casbboy** [comment]
Ok. so replace the entire line with just what you added? I noticed post.xml was gone. Would we need to a wildcard for the post.xml, since that becomes post_part2.xml when BWP starts breaking the posts sitemap into multiple pages.

**Comment by amiga-500** [comment]
Oh sorry my mistake...yes my mistake..i just noticed i did forget about post.xml...let me rewrite things for you.

**Comment by amiga-500** [comment]
Hi @casbboy  Ok you can try:

```php
(sitemapindex|post|site|page|taxonomy_category)(_part[0-9]+)?\.xml
```

Notice i included "post" and i also included the potential for "_part2" (or _part3,...)

**Comment by casbboy** [comment]
Sweet! Going to try now.

**Comment by casbboy** [comment]
So weird, I changed the rules and they once again worked for the post.xml, but the sitemapindex.xml was left cached. Not sure why that is happening, as the line is right.

**Comment by amiga-500** [comment]
Sounds like it could be related to either you having a server-side reverse proxy like Varnish existing (e.g. for mine i need to tell varnish to purge or i wont see the latest _sitemapindex.xml_) or browser-side cache temporarily just showing you the old results.  Not sure how much changes inside _sitemapindex.xml_ but for me the only thing i see changed is the date for _post.xml_

**Comment by casbboy** [comment]
Yeah, it will show the update time on the sitemap for post.xml updated, telling Google to index it again. I don't use Varnish, and my browser is set to no-cache. I can keep refreshing and it shows the same. But if I clear all disk cache, immediately shows the file updated in browser.

So strange. It's definitely not clearing it.

**Comment by amiga-500** [comment]
Strange indeed.  I am even using your same settings  (and BWP) to simulate and its all working fine (sitemapindex.xml is being deleted fine).   The only thing i haven't tested it against is by having CloudFlare enabled which you do and i don't.  I will go create a CloudFlare account so at least config wise we will be identical, and maybe i will get lucky and the sitemapindex.xml will now not delete making it then easier for me to know what is wrong.  Not sure why it wouldn't delete still in this context but hey might as well try since everything else is working fine so i need something.

**Comment by casbboy** [comment]
I actually have Cloudflare set to bypass *.xml files to ensure that isn't the case. :(

It has to be something local. Grrrrrrrrrr

**Comment by amiga-500** [comment]
Thanks for the info.  I will keep roaming for some answers.  Odd that the other files get removed except for sitemapindex.xml ... so close 😿  ... at least we're almost there!

In the mean time, if you learn anything new about a potential cause or resolve it please let me know asap.

**Comment by charlesLF** [comment]
@casbboy: I am assuming you are using "Disk Cache: Enhanced", correct?
Have you tried looking in your cache directory (usually in /wp-content/cache/page_enhanced) after you publish a new post?

Is there a file/folder related to sitemapindex.xml anywhere there?

**Comment by casbboy** [comment]
Let me check, but yes, I am using that. For some reason the memcache option kept crashing my memcache.

**Comment by casbboy** [comment]
Ok, when I go into that folder, i see the sitemapindex.xml folder being created when I publish a new post, but no post.xml folder is being created upon posting. Then, when I go to the post.xml sitemap, I then see "post.xml" folder being created. But only after I visit the sitemap, while sitemapindex.xml is there before needing to be opened.

**Comment by casbboy** [comment]
Another weird error worth noticing. Is that before clearing cache manually, my browser reads the sitemapindex.xml as bad format (like the xml header didn't come through). But when I clear disk cache and open again the format is considered correct.

**Comment by casbboy** [comment]
Another thing I'm seeing is that it immediately pings the search engines with the sitemapindex.xml on publishing. Not sure what issue this might cause.

**Comment by amiga-500** [comment]
Hi @casbboy 

Not sure if you will be around.  Here are some info  for ya:

> _Another thing I'm seeing is that it immediately pings the search engines with the sitemapindex.xml on publishing. Not sure what issue this might cause._

Under _**BWP Sitemaps > XML Sitemaps (tab) > Ping Search Engines**_ you probably have those checked on.  When you make a new post they will auto-ping.  Also Wordpress' pings too on new posts: _**Settings > Writing > Update Services**_

> _Another weird error worth noticing. Is that before clearing cache manually, my browser reads the sitemapindex.xml as bad format (like the xml header didn't come through). But when I clear disk cache and open again the format is considered correct._

Go to: _Performance > Page Cache > Advanced >_ **Handle XML mime Type**  (checkmark/enable this on).  This seems to indicate that the file is being sent back with the incorrect mime type.  When you clear disk cache and re-open the file it's fine because it is recaching it and returning it back as an xml type.  But once cached it is returning it back as html.  I fixed this issue on Apache servers but noticed the original w3tc author had this already available for nginx.  What left me scratching my head was he purposely prevents using this feature under a certain condition -- its been a while so i forget.

> _Ok, when I go into that folder, i see the sitemapindex.xml folder being created when I publish a new post, but no post.xml folder is being created upon posting. Then, when I go to the post.xml sitemap, I then see "post.xml" folder being created. But only after I visit the sitemap, while sitemapindex.xml is there before needing to be opened._
   
What is strange is why the sitemapindex.xml is being generated automatically when you publish.  On my side nothing gets generated until someone visits the sitemap.  It seems someone is attempting to access it right away on publish.  It could be one of the ping services immediately pinging back the sitemapindex.xml on publish since you seem to have the pinging service enabled.  That being said it seems sitemapindex.xml, ping.xml, and any other related xml files are indeed getting removed on your side correctly when published.  It's just that the sitemap cache is being generated in the wrong order:

When the sitemapindex.xml file is generated so quickly it is done before post.xml is created (or any of the other xml files held inside sitemapindex.xml), this results in sitemapindex.xml showing the old timestamps for the other xml files.  In short, it's like we want to auto-generate the other xml files upon a new publish and then generate sitemapindex.xml last (or not generate it automatically at all, relying on someone hitting the file to generate).  I will have to play around to see what we can do.  It's possible we might need you to have BWP cache the sitemap instead.  This to me could resolve your problem.

**Comment by charlesLF** [comment]
I have to agree with @amiga-500's detailed analysis.

@casbboy: One thing you can do to help us narrow it down:

1. Go to the cache directory `/wp-content/cache/page_enhanced`
2. Check the creation date of the sitemapindex.xml folder
3. Publish a new post
4. Re-check the creation date of the sitemapindex.xml folder
5. Is the date newer? If so, then w3tc is correctly clearing the cache, and the problem may well be from how BWP pings the sitemap when a new post is published.

Let us know what you find out :)

**Comment by casbboy** [comment]
First, if I go here: Performance > Page Cache > Advanced > Handle XML mime Type

It won't let me add a checkmark, it looks disabled.

I added "sitemapindex.xml" to Additional Pages in page cache.

Second, I checked and folder existed:

sitemapindex.xml 20161208 19:32

I added a post and checked again

sitemapindex.xml 20161208 19:45

So it updated on post. Then I opened the page and the formatting was right. So everything looked good, but it showed the last modified date for post.xml as 16:44

I manually cleared disk cache and opened sitemapindex.xml again and it showed modified date for post.xml as 19:45

So still something a bit off. But closer!

Cheers
Ryan

**Comment by casbboy** [comment]
Actually, made another discovery.

So even with W3TC ignoring cacheing sitemapindex.xml, it still does not update the Modified Time on the file with new post, so not a cache issue. 

The problem seems BWP itself, as it does not regenerate the sitemapindex.xml file in regards to modified time until a listed sitemap is once again opened.

So, it will not update until I open a purged post.xml. When I open that, it then tells sitemapindex.xml to rebuild on its most recent modified/added post.

Cheers!
Ryan

**Comment by amiga-500** [comment]
Precisely...that is what i discovered this morning.  Glad you made that discovery too!  It's a design flaw within BWP.  I ended up attempting to contact the author earlier this morning when i realized it was a problem with his code.   He hasn't replied yet.

**Comment by charlesLF** [comment]
Awesome! Thanks for the info.

While you're waiting for the BWP author to push a fix, here's what you can do to workaround your problem.

Add the following code somewhere in your theme's `functions.php`:

```
add_action('publish_post','reclear_w3tc_fix_cache',9999999);

function reclear_w3tc_fix_cache() {
	if(!function_exists('w3_instance')) { return false; }
	$pgcacheflush = w3_instance('W3_PgCacheFlush');
	$cache = $pgcacheflush->_get_cache();
	$cache->flush('sitemaps');
}
```

Basically, we're flushing the sitemap page cache once again when a post is published (firing the hook _after_ BWP has done its pinging)

I haven't tried this myself, so let me know if it does work for you.
