### ISSUE TITLE
nginx: feed returns wrong content type

### ISSUE THREAD

**Issue by danwie** [szepeviktor/fix-w3tc#449]
First time I access www.mydomain.com/feed/ the response headers returns: `Content-Type:application/rss+xml; charset=UTF-8`. But when I request again it returns `Content-Encoding:gzip`. What could be wrong?

ls:
```
drwxr-xr-x  2 www-data www-data  4096 Mar 23 09:57 .
drwxr-xr-x 16 www-data www-data  4096 Mar 23 09:54 ..
-rw-r--r--  1 www-data www-data 36007 Mar 23 09:57 _index_ssl.html
-rw-r--r--  1 www-data www-data 10314 Mar 23 09:57 _index_ssl.html_gzip
```

In settings "Performance" I've enabled "Cache feeds: site, categories, tags, comments". 
In "Browser Cache" I've enabled "Enable HTTP (gzip) compression". 

I'm using:
- Disk: enhanced. 
- Wordpress 4.7.3, 
- W3TC Fixed 0.9.5.2.3
- Nginx and PHP-FPM
- PHP Version 5.3.29-1~dotdeb.0

there are two issues:
1. [x] ~~[option "handle the xml" is always disabled on nginex](https://github.com/szepeviktor/w3-total-cache-fixed/pull/454)~~
2. [ ] cached feed returns wrong content type (text/html)

**Comment by danwie** [comment]
Maby related to https://github.com/szepeviktor/w3-total-cache-fixed/pull/393

**Comment by nigrosimone** [comment]
You have checked "handle xml mime type"?

**Comment by danwie** [comment]
Yes, it is checked. It seems to be checked by default. Checkbox is disabled so I'm unable to uncheck it.

![image](https://cloud.githubusercontent.com/assets/807280/24247805/71954cfa-0fcd-11e7-9f2f-ede4c24ea846.png)

**Comment by nigrosimone** [comment]
@danwie after digging into the code i found the problem. W3TC with Disk enhanced, handle the xml only if the webserver is Apache, see https://github.com/szepeviktor/w3-total-cache-fixed/blob/v0.9.5.x/Cache_File_Generic.php#L86

**Comment by danwie** [comment]
Then I understand. Would it be possible to put this on the todo list? I'm guessing that most people want to cache the feed, and that most people use Disk enhanced.

**Comment by nigrosimone** [comment]
you are right, i have tagged this topic with "Feature Request" label.

Thanks.

**Comment by szepeviktor** [comment]
@nigrosimone Could you find a way to contact W3TC for a new release? Our changelog is huge!

**Comment by nigrosimone** [comment]
I send a mail every new change but w3tc doesn't respond from one month ago.

**Comment by szepeviktor** [comment]
OK.

Maybe monthly 1 mail will not overwhelm them.

**Comment by nigrosimone** [comment]
hey @danwie, i'm on work!

It's my first time on nginex and i need a bit of help from you :)

Now, i found the issue...

@amiga-500 in the https://github.com/szepeviktor/w3-total-cache-fixed/pull/393 has already implemented the feature (handle the xml for both apache and nginex) but has introduced a small issue: the option (handle the xml) is always disabled/false on nginex. Now, i have fixed this small issue by a bit of refracoring https://github.com/szepeviktor/w3-total-cache-fixed/pull/454/files.

Now, you can allow xml handling on nginex (after check and save the settings). W3TC store the feed cache in the right way 
![immagine](https://cloud.githubusercontent.com/assets/310077/24321124/da95545c-1144-11e7-9441-60adcc0d4689.jpg)

but nginex always response in the wrong way (text/html instead of application/xml)
![immagine2](https://cloud.githubusercontent.com/assets/310077/24321130/11ecb490-1145-11e7-919b-e54f41340d96.jpg)

fix this, require some changes in the w3tc nginex .conf, because every file with *gzip is server how text/html;
```
# BEGIN W3TC Page Cache cache
location ~ /wp-content/cache/page_enhanced.*html$ {
}
location ~ /wp-content/cache/page_enhanced.*gzip$ {
	gzip off;
	types {}
	default_type text/html;
	add_header Content-Encoding gzip;
}
# END W3TC Page Cache cache
```

i have tried some fix like
```
# BEGIN W3TC Page Cache cache
location ~ /wp-content/cache/page_enhanced.*html$ {
}
location ~ /wp-content/cache/page_enhanced.*xml$ {
}
location ~ /wp-content/cache/page_enhanced.*html_gzip$ {
	gzip off;
	types {}
	default_type text/html;
	add_header Content-Encoding gzip;
}
location ~ /wp-content/cache/page_enhanced.*xml_gzip$ {
	gzip off;
	types {}
	default_type application/xml;
	add_header Content-Encoding gzip;
}
# END W3TC Page Cache cache
```
but doesn't work... can you help me?

I have update the master with admin setting fix.

**Comment by danwie** [comment]
Great work. Thank you! The solution is to use a different order. This should work:

```nginx
# BEGIN W3TC Page Cache cache
location ~ /wp-content/cache/page_enhanced.*xml$ { # NEW
}
location ~ /wp-content/cache/page_enhanced.*xml_gzip$ { # NEW
}
location ~ /wp-content/cache/page_enhanced.*html$ {
}
location ~ /wp-content/cache/page_enhanced.*gzip$ { # NOTE: It should be better to catch all instead of *html_gzip$. We shouldn't change this behaviour in my opinion. But maby both ways are working.
}
# END W3TC Page Cache cache
```

I also think it should return content type `application/rss+xml`

Not sure if this is related. But I also noticed that feed (/feed/ folder) is not purged when updating/publishing new posts. I've checked all the boxes for rdf, rss, rss2 (default) and atom.

**Comment by nigrosimone** [comment]
@danwie these rules doesn't works for me:

```
# BEGIN W3TC Page Cache cache
location ~ /wp-content/cache/page_enhanced.*xml$ {
}
location ~ /wp-content/cache/page_enhanced.*xml_gzip$ {
	gzip off;
	types {}
	default_type application/xml;
	add_header Content-Encoding gzip;
}
location ~ /wp-content/cache/page_enhanced.*html$ {
}
location ~ /wp-content/cache/page_enhanced.*html_gzip$ {
	gzip off;
	types {}
	default_type text/html;
	add_header Content-Encoding gzip;
}
# END W3TC Page Cache cache
```

**Comment by danwie** [comment]
I'm attaching screenshots of what's working for me. Maby you forgot to restart nginx?

![image](https://cloud.githubusercontent.com/assets/807280/24394445/559e1c0c-139c-11e7-9bb2-b6c7b9ac9f3f.png)
![image](https://cloud.githubusercontent.com/assets/807280/24394454/5ac8b4da-139c-11e7-96fc-2c4f15e9a995.png)
![image](https://cloud.githubusercontent.com/assets/807280/24394463/5ef05a0e-139c-11e7-8b1d-0b1b3562e723.png)

**Comment by danwie** [comment]
@nigrosimone Still not working for you? Let me know what I can do to help.

**Comment by nigrosimone** [comment]
Nope... on my dev machine still not working.

**Comment by charlesLF** [comment]
@nigrosimone: just to be sure, are you including the w3tc-generated nginx.conf in your main site's nginx conf file?

I typically include it just before the "location /" block in the site's conf file.

**Comment by nigrosimone** [comment]
@charlesLF, this is my full `nginx.conf`, thanks for the help!


```
#user  nobody;
worker_processes  1;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    #gzip  on;

    server {
        listen       80;
        server_name  localhost;

        #charset koi8-r;

        #access_log  logs/host.access.log  main;
		
		root C:\DevEnv\htdocs\www.wordpress.local;
        index index.php index.html index.htm;

        location / {
            # try_files $uri $uri/ =404;
            try_files $uri $uri/ /index.php?q=$uri&$args;
        }

        #error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
		

        # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9123
        #
        location ~ \.php$ {
		    try_files $uri =404;
            fastcgi_split_path_info ^(.+\.php)(/.+)$;
            fastcgi_pass   127.0.0.1:9123;
            fastcgi_index index.php;
			fastcgi_param  SCRIPT_FILENAME  C:\DevEnv\htdocs\www.wordpress.local$fastcgi_script_name;
            include fastcgi_params;
        }

        # deny access to .htaccess files, if Apache's document root
        # concurs with nginx's one
        #
        location ~ /\.ht {
            deny  all;
        }
		
		# BEGIN W3TC Minify cache
		location ~ /wp-content/cache/minify/.*\.js$ {
			types {}
			default_type application/x-javascript;
			add_header Vary "Accept-Encoding";
		}
		location ~ /wp-content/cache/minify/.*\.css$ {
			types {}
			default_type text/css;
			add_header Vary "Accept-Encoding";
		}
		location ~ /wp-content/cache/minify/.*js\.gzip$ {
			gzip off;
			types {}
			default_type application/x-javascript;
			add_header Vary "Accept-Encoding";
			add_header Content-Encoding gzip;
		}
		location ~ /wp-content/cache/minify/.*css\.gzip$ {
			gzip off;
			types {}
			default_type text/css;
			add_header Vary "Accept-Encoding";
			add_header Content-Encoding gzip;
		}
		# END W3TC Minify cache
		# BEGIN W3TC Minify core
		set $w3tc_enc "";
		if ($http_accept_encoding ~ gzip) {
			set $w3tc_enc .gzip;
		}
		if (-f $request_filename$w3tc_enc) {
			rewrite (.*) $1$w3tc_enc break;
		}
		rewrite ^/([a-z0-9]+/)?wp-content/cache/minify/ /index.php last;
		# END W3TC Minify core
		# BEGIN W3TC Page Cache core
		set $w3tc_rewrite 1;
		if ($request_method = POST) {
			set $w3tc_rewrite 0;
		}
		if ($query_string != "") {
			set $w3tc_rewrite 0;
		}
		if ($request_uri !~ \/$) {
			set $w3tc_rewrite 0;
		}
		if ($http_cookie ~* "(comment_author|wp\-postpass|w3tc_logged_out|wordpress_logged_in|wptouch_switch_toggle)") {
			set $w3tc_rewrite 0;
		}
		if ($http_user_agent ~* "(W3\ Total\ Cache)") {
			set $w3tc_rewrite 0;
		}
		set $w3tc_preview "";
		if ($http_cookie ~* "(w3tc_preview)") {
			set $w3tc_preview _preview;
		}
		set $w3tc_enc "";
		if ($http_accept_encoding ~ gzip) {
			set $w3tc_enc _gzip;
		}
		if (!-f "$document_root/wp-content/cache/page_enhanced/$http_host/$request_uri/_index$w3tc_preview.html$w3tc_enc") {
		  set $w3tc_rewrite 0;
		}
		if ($w3tc_rewrite = 1) {
			rewrite .* "/wp-content/cache/page_enhanced/$http_host/$request_uri/_index$w3tc_preview.html$w3tc_enc" last;
		}
		# END W3TC Page Cache core
		# BEGIN W3TC Page Cache cache
		location ~ /wp-content/cache/page_enhanced.*xml$ {
		}
		location ~ /wp-content/cache/page_enhanced.*xml_gzip$ {
			gzip off;
			types {}
			default_type text/xml;
			add_header Content-Encoding gzip;
		}
		location ~ /wp-content/cache/page_enhanced.*html$ {
		}
		location ~ /wp-content/cache/page_enhanced.*html_gzip$ {
			gzip off;
			types {}
			default_type text/html;
			add_header Content-Encoding gzip;
		}
		# END W3TC Page Cache cache
		# BEGIN W3TC Browser Cache
		gzip on;
		gzip_types text/css text/x-component application/x-javascript application/javascript text/javascript text/x-js text/richtext image/svg+xml text/plain text/xsd text/xsl text/xml image/bmp application/java application/msword application/vnd.ms-fontobject application/x-msdownload image/x-icon image/webp application/json application/vnd.ms-access application/vnd.ms-project application/x-font-otf application/vnd.ms-opentype application/vnd.oasis.opendocument.database application/vnd.oasis.opendocument.chart application/vnd.oasis.opendocument.formula application/vnd.oasis.opendocument.graphics application/vnd.oasis.opendocument.spreadsheet application/vnd.oasis.opendocument.text audio/ogg application/pdf application/vnd.ms-powerpoint application/x-shockwave-flash image/tiff application/x-font-ttf audio/wav application/vnd.ms-write application/font-woff application/font-woff2 application/vnd.ms-excel;
		add_header Referrer-Policy "";
		# END W3TC Browser Cache
    }


    # another virtual host using mix of IP-, name-, and port-based configuration
    #
    #server {
    #    listen       8000;
    #    listen       somename:8080;
    #    server_name  somename  alias  another.alias;

    #    location / {
    #        root   html;
    #        index  index.html index.htm;
    #    }
    #}


    # HTTPS server
    #
    #server {
    #    listen       443 ssl;
    #    server_name  localhost;

    #    ssl_certificate      cert.pem;
    #    ssl_certificate_key  cert.key;

    #    ssl_session_cache    shared:SSL:1m;
    #    ssl_session_timeout  5m;

    #    ssl_ciphers  HIGH:!aNULL:!MD5;
    #    ssl_prefer_server_ciphers  on;

    #    location / {
    #        root   html;
    #        index  index.html index.htm;
    #    }
    #}

}
```
